### PR TITLE
Event page is updated

### PR DESCRIPTION
**Pull request by Rengaraj**
July meetup schedule is added to event page #89

### CODE REVIEW

**Comment by shrayasr** [comment]
:+1: This closes #89 also

**Comment by Rengaraj** [comment]
@shrayasr why travis CI was not run for this PR #90

**Comment by shrayasr** [comment]
Not really sure, probably I didn't give it time to run, went through the post and then merged it

**Comment by shrayasr** [comment]
Aha. @Rengaraj I seem to have missed a tiny detail here. The link from the home page should go to the internal July meetup page and not to meetup.com. Please fix that and send another PR? Thanks. 

Sorry for not noticing.

**Comment by Rengaraj** [comment]
Ho Ho ok . will do that

**Comment by Rengaraj** [comment]
Changed in PR #91

**Pull request merged**
