### PR TITLE
Adding Disqus Comments

### PR DESCRIPTION
**Pull request by kskrishnasangeeth**
- Updating <code>pelicanconf.py </code> to include disqus sitename.

### CODE REVIEW

**Comment by shrayasr** [comment]
Hey,

I'm not really sure adding comments to the website as of this point in time might be a good idea. Once the site starts generating some traffic, then I think comments make sense. Otherwise would just be empty boxes with 1/2 comments everywhere. 

@bravegnu, your thoughts?

**Comment by kskrishnasangeeth** [comment]
@shrayasr  I got your point from a design perspective of keeping things simple. But i was thinking in terms of 
- we are already having many comments in meetup group, I personally feel that having those comments in the minutes page of the website makes greater sense .

**Comment by shrayasr** [comment]
> we are already having many comments in meetup group, I personally feel that having those comments in the minutes page of the website makes greater sense .

The comments in the meetup group aren't really all that relevant to the minutes also. 

> I got your point from a design perspective of keeping things simple. 

Also the point that I was making wasn't from a design perspective or to keep things simple. What I meant was the necessity of a discussion engine on the website. 

---

A side thought would be to add Google Analytics first to understand the traffic on the minutes pages. And then take a decision, what do you think?

**Comment by kskrishnasangeeth** [comment]
Alrighty . Let's first try to get some data on how much traffic we are getting on the minutes pages.

**Comment by shrayasr** [comment]
Yup. That makes more sense. I've open another issue for that already

**Comment by bravegnu** [comment]
@kskrishnasangeeth thanks for coming up with suggestions. Here is my thoughts on this.

The purpose of comments is to give feedback about an article. Usually this is required for technical articles. And I don't think we are going to put up technical articles on the Chennaipy website.

Also, if there are any improvements that need to be made to the article, they can be created as issues on GitHub.

Any other discussions, should happen on the mailing list.

**Comment by kskrishnasangeeth** [comment]
:+1:

**Pull request closed without merging**
