### PR TITLE
Adding video links to all JAN talks

### PR DESCRIPTION
**Pull request by shrayasr**
Also edited the minutes

### CODE REVIEW

**Comment by kirang89** [comment]
Some of the talk descriptions start with *"\<Speaker name\> talked about"* while others start with *"He talked about"*. I'd suggest using a single format for the sake of consistency. Just a quick suggestion :)

**Comment by shrayasr** [comment]
Sure. Will fix :)

**Comment by shrayasr** [comment]
Done

**Comment by kirang89** [comment]
Thank you good sir!

**Comment by shrayasr** [comment]
:smile:

**Pull request merged**
