### PR TITLE
Prototype Frontpage Implementation.

### PR DESCRIPTION
**Pull request by bravegnu**

### CODE REVIEW

**Comment by bravegnu** [comment]
Guys, your comments on this ...

**Comment by shrayasr** [comment]
Sorry for the lateness. Been really busy this week at office. 

This is **way** more "scalable" than what we currently have but I think it becomes a little too bland. There is just way too much text going on in the page. We should find the right balance IMO between using text and not using it. I really like PyCh.in and we could learn from them. They have a good balance going on with dashes of colour. 

Please note, in no way am I criticizing what you have done. This is a great effort and should be done. The only sad part is none of us are designers and I don't know if we have any one on the team that is who can help us out with this. 

Let me also give this a try and we can probably borrow thoughts from our work and decide on a final version?

**Comment by bravegnu** [comment]
OK. I will try to explain why we started doing this, and why ended up doing this.

  * First, we wanted a page that can hold links to all other pages in the website. That was what I proposed in #47 The current pelican theme only provides a sidebars with few links that does has proved to be insufficient in many instances, as noted by @shrayasr in the same issue.

  * Since we started re-doing the front page, we decided to borrow some cues from other sites, like Pych, PyCon India, etc.

  * I do agree that this prototype needs improvement in the design department. But if you think this would serve as meaningful starting point, then I would prefer getting this committed, and then  improving upon it. The page will remain hidden, till the time it is satisfactory. At which point we will turn the home.html to index.html and go public.

**Comment by shrayasr** [comment]
>     First, we wanted a page that can hold links to all other pages in the website. That was what I proposed in #47 The current pelican theme only provides a sidebar with few links that has proved to be insufficient in many instances, as noted by @shrayasr in the same issue.

:+1:
 
>     Since we started re-doing the front page, we decided to borrow some cues from other sites, like Pych, PyCon India, etc. But our intentions might be much different from theirs.

Fair enough. But what I meant was the direction that we need to take eventually. 
 
>     I do agree that this prototype needs improvement in the design department. But if you think this would serve as meaningful starting point, then I would prefer getting this committed, and then improving upon it. The page will remain hidden, till the time it is satisfactory. At which point we will turn the home.html to index.html and go public.

Yes I noticed that it is in `home.html` and that it wont replace `index.html`. If it anyway doesn't come up on the site then why do we really need to commit it in? We can just keep this as a WIP place and work on it, right? Like you mentioned lets use this as a starting point and work on it here. I don't see the necessity to merge it in if it isn't going live anyway ATM. Right?

**Comment by igauravsehrawat** [comment]
how about we look for new theme the same way we looked for logo ?

**Comment by shrayasr** [comment]
> how about we look for new theme the same way we looked for logo ?

-1 from me on this. It'll become too much of an elaborate process then.

**Comment by shrayasr** [comment]
@bravegnu Why is this closed? Lets continue our frontpage discussion here. ok?

**Comment by bravegnu** [comment]
Can we discuss in the issue #47 instead?

**Comment by shrayasr** [comment]
Ah, sure.

**Pull request closed without merging**
