### PR TITLE
End of april meetup

### PR DESCRIPTION
**Pull request by shrayasr**
What a debate. Phew.

### CODE REVIEW

**Comment by shrayasr** [comment]
@Chennaipy/web-team

**Comment by bravegnu** [comment]
Zen of Python Meetups: Avoid political discussions at Python meetups.

**Comment by kskrishnasangeeth** [comment]
Haha. That's clever :-)

**Comment by shrayasr** [comment]
> Zen of Python Meetups: Avoid political discussions at Python meetups.

+1

**Pull request merged**
