### PR TITLE
Adding Tracking code to publishconf.py 

### PR DESCRIPTION
**Pull request by kskrishnasangeeth**
There was a field in <code>publishconf.py</code> with name <code>GOOGLE_ANALYTICS</code> . Noticed it just now, I have updated this also with tracking code for fixing #51

### CODE REVIEW

**Comment by shrayasr** [comment]
Aha. I was wondering why analytics didn't come in. 

It isn't necessary in the `pelicanconf.py` then, right? We don't want everyone who clones and runs it locally to be giving in to the analytics.

**Comment by kskrishnasangeeth** [comment]
I am not exactly sure on this @shrayasr

So I tried a bit of experiment.

* Commented Google Analytics on <code>pelicanconf.py</code>
* Updated tracking code on <code>publishconf.py</code>

When i did this , the [javascript](http://pastebin.com/hmAt0z9W) part that does the tracking was not found in our pages created by pelican.

So my guess is same as yours. If we are having it updated in <code>pelicanconf.py</code> , then we can see the tracking JS part in our pages and people who use it in local might contribute to analytics. But if we are having it only in <code>publishconf.py</code> , then pelican might push the JS only to the publishing environment.

Also i see that the tracking has already been installed in the admin page.

analytics

**Comment by shrayasr** [comment]
> So my guess is same as yours. If we are having it updated in pelicanconf.py , then we can see the tracking JS part in our pages and people who use it in local might contribute to analytics. But if we are having it only in publishconf.py , then pelican might push the JS only to the publishing environment.

Great. This is what we need. Why dont you go ahead and remove it from `pelicanconf.py` and keep it only in `publishconf.py`? That would give us the desired behaviour

**Comment by kskrishnasangeeth** [comment]
Yeah that sounds ideal. Closing this. Will send a separate PR.

**Comment by shrayasr** [comment]
You could've done it in this only boss. Just pushing more commits to your `google-analytics` branch will update this PR :)

**Comment by kskrishnasangeeth** [comment]
Yeah I could have. I am still a Noob  I think when it comes to actually using Github. :-) Sorry for the confusion.

**Comment by shrayasr** [comment]
Haha. No issues, you can just push your changes to the `google-analytics` branch on your fork and reopen this same PR. I think that should work

**Comment by kskrishnasangeeth** [comment]
What about the new PR I send in between. ? It would be easier if you could
merge that one.

**Comment by shrayasr** [comment]
Merged #56 :)

**Pull request closed without merging**
